server:
  port: 9090

spring:
  application:
    name: app-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo_users
    username: root
    password:
  sql:
    init:
      mode: always #fuerza a ejecutar data.sql
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true #espera que hibernate cree las tablas

logging:
  level:
    org:
      hibernate:
        sql: debug